name:                dpq
version:             0.0.1.0
github:              "https://gitlab.com/frank-peng-fu/dpq-remake.git"
license:             BSD3
author:              "Frank (Peng) Fu, Kohei Kishida, Neil J. Ross, Peter Selinger"
maintainer:          "peng.frank.fu@gmail.com, selinger@mathstat.dal.ca"
copyright:           "2019"

extra-source-files:
- README.md
- ChangeLog.md

data-files:          lib/*.dpq,
                     test/*.dpq


# Metadata used when publishing your package
synopsis: Dependently typed Proto-Quipper (Proto-Quipper-D)

category:            Programming language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
        A linear dependent typed language for quantum circuit programming.   
        Please see the README at <https://gitlab.com/frank-peng-fu/dpq-remake#readme>
        for more information. 

homepage:   https://gitlab.com/frank-peng-fu/dpq-remake           

dependencies:
- base >= 4.7 && < 5
- containers
- multiset
- parsec
- indents
- transformers
- mtl
- pretty
- haskeline
- filepath
- easyrender
- directory
- process
- nominal

library:
  source-dirs: src

executables:
  dpqi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    dependencies:
    - dpq

  dpq:
    main:                Main.hs
    source-dirs:         executable
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    dependencies:
    - dpq

tests:
  dpq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dpq
